### PR TITLE
Fix model deploy for SKLearn

### PR DESCRIPTION
**Pull request by ybenitezf**
This will deploy the endpoint correctly to AWS Sagemaker using the recipe from the [sagemaker sklearn documentation](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#deploy-an-endpoint-from-model-data)

Adds a new script to used during model serving to load the model, see `model_loader.py`

The endpoint is deployed correctly, but calling the endpoint there are errors, for example:

```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
    return fn(*args, **kwargs)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 70, in default_predict_fn
    output = model.predict(input_data)
  File "/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 307, in predict
    scores = self.decision_function(X)
  File "/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 282, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 623, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[0.18659  0.18659  0.74449  0.74449  0.74449  0.00193  0.61674  0.06314
 0.04719  0.00402  0.       0.00701  0.00701  0.0125   0.00701  0.18659
 0.0125   0.00701  0.277982 0.0125   0.0125   1.       0.06314 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```  

I think this has to do with the format of the data send to the endpoint or the lack of the functions [mentioned on the documentation](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#serve-a-model) in the `model_loader.py`

### CODE REVIEW

**Comment by ybenitezf** [comment]
@sorice  or @leonel-lordford I think what is missing here is to [implement those functions](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#serve-a-model) in `model_loader.py` or to test to see if the data is being sent to the endpoint wrong.

Don't remove the commented code in `deploymodel.py`

**Comment by ybenitezf** [comment]
Forgot to mention that the model package group was renamed to `sts-sklearn-grp`

**Comment by leonel-lordford** [comment]
> mentioned on the documentation

Makes a little sense, at least the log reports what we can try, reshaping is something quite easy, so let's try it...

**Comment by leonel-lordford** [comment]
> @sorice or @leonel-lordford I think what is missing here is to [implement those functions](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#serve-a-model) in `model_loader.py` or to test to see if the data is being sent to the endpoint wrong.
> 
> Don't remove the commented code in `deploymodel.py`

Everywhere I see references to these functions :-D but not too many places show complete examples etc... we need to try it, it's the same for Torch models...

We need to try it.

**Comment by ybenitezf** [comment]
> > @sorice or @leonel-lordford I think what is missing here is to [implement those functions](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#serve-a-model) in `model_loader.py` or to test to see if the data is being sent to the endpoint wrong.
> > Don't remove the commented code in `deploymodel.py`
> 
> Everywhere I see references to these functions :-D but not too many places show complete examples etc... we need to try it, it's the same for Torch models...
> 
> We need to try it.

Those functions, with should be passed to the framework in a script - `model_loader.py` in this case - should be implemented for each algorithm. I think that for xgboost and sklearn there are defaults in place.

**Comment by ybenitezf** [comment]
[from the docs](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#serve-a-model):

> The SageMaker Scikit-learn model server provides default implementations of these functions. You can provide your own implementations for these functions in your hosting script. If you omit any definition then the SageMaker Scikit-learn model server will use its default implementation for that function.

**Comment by leonel-lordford** [comment]
Good! In that case, we just need to pack the model in the "standard" format... the expected format... which is the default if we use the SM mechanism :-D

**Pull request merged**
